### ISSUE TITLE
Spivak, Spivak and Fong books

### ISSUE THREAD

**Issue by austinvhuang** [saurabhkukade/Haskell_Study#2]
Category Theory for Scientists by David Spivak (draft version) - https://ocw.mit.edu/courses/mathematics/18-s996-category-theory-for-scientists-spring-2013/textbook/MIT18_S996S13_textbook.pdf

Seven Sketches in Compositionality - http://math.mit.edu/~dspivak/teaching/sp18/7Sketches.pdf

Side note - might it be better to link to the sources? That way if the authors have updates they'll be reflected. Also the repo won't get bloated with old versions of the pdfs if you update.

**Comment by saurabhkukade** [comment]
Thanks for the references and I have added them to repository.
And yes it might be better to link to the sources. I did not expect the this much response to my repository hence I kept pdfs directly into repo. 
But going forward I will try to keep the link to sources. 
Thanks again!!

**Comment by saurabhkukade** [comment]
I have added them to repository.
